#### Constant tensors and variables

In [ ]:
# All-ones
import tensorflow as tf

x = tf.ones((2, 3))
print(x)  # <tf.Tensor: shape=(2, 3), dtype=float32, numpy=...>

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [2]:
# All-zeros
x = tf.zeros((2, 3))
print(x)  # <tf.Tensor: shape=(2, 3), dtype=float32, numpy=...>

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [7]:
# Random tensors
x = tf.random.uniform((2, 3), minval=0, maxval=1) # between 0 and 1
print(x)  # <tf.Tensor: shape=(2, 3), dtype=float32, numpy=...>
print()
x = tf.random.normal((2, 3), mean=0, stddev=1) # Mean 0 and standard deviation 1.
print(x)  # <tf.Tensor: shape=(2, 3), dtype=float32, numpy=...>

tf.Tensor(
[[0.19700003 0.34295905 0.18798995]
 [0.37888336 0.7020986  0.51890755]], shape=(2, 3), dtype=float32)

tf.Tensor(
[[ 1.6992557  -0.86809254 -0.29524034]
 [-0.64603335 -0.589915    1.2588973 ]], shape=(2, 3), dtype=float32)


A significant difference between NumPy arrays and TensorFlow tensors is that Tensor-
Flow tensors aren’t assignable: they’re constant.

In [ ]:
# NumPy arrays are assignable
import numpy as np
x = np.ones((2, 3))
x[0, 0] = 0
print(x)  # [[0. 1. 1.] [1. 1. 1.]]

[[0. 1. 1.]
 [1. 1. 1.]]


In [11]:
# TensorFlow tensors are not assignable
x = tf.ones((2, 3))
x[0, 0] = 0  # Error: Tensor is immutable
print(x)  # <tf.Tensor: shape=(2, 3), dtype=float32, numpy=...>

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [31]:
# Creating a TensorFlow variable
print('Creating a TensorFlow variable:')
x = tf.Variable(tf.random.normal((2, 3))) #To create a variable, you need to provide some initial value, such as a random tensor.
x[1, 1].assign(99)  # Assigning a value to a variable
print(x)  # <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=...>

# The state of a variable can be modified via its assign method, as follows.
print(f'\nAssigning a value to a TensorFlow variable:')
x.assign(tf.ones((2, 3)))  # Assigning a new value to the variable
print(x)  # <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=...>

print(f'\nAssigning a value to a subset of a TensorFlow variable:')
x[0, 1].assign(99)  # Assigning a value to a specific element of the variable
print(x)  # <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=...>

Creating a TensorFlow variable:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[-4.3386579e-01,  5.7397783e-01,  2.8143653e-01],
       [ 4.0824185e-03,  9.9000000e+01, -9.6249193e-01]], dtype=float32)>

Assigning a value to a TensorFlow variable:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

Assigning a value to a subset of a TensorFlow variable:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 1., 99.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)>


#### Tensor operations: Doing math in TensorFlow

In [39]:
# Just like NumPy, TensorFlow offers a large collection of tensor operations to express mathematical formulas.
a = tf.random.normal((2, 3)) # 2x3 tensor of ones
print(f'Tensor: \n{a}')  # <tf.Tensor: shape=(2, 3), dtype=float32, numpy=...>
b = tf.square(a) # Take the square of each element
print(f'\nSquare:\n {b}')  # <tf.Tensor: shape=(2, 3), dtype=float32, numpy=...>

Tensor: 
[[ 0.42061698  1.4794505  -0.48010027]
 [-0.51857364  1.8386749   0.15671276]]

Square:
 [[0.17691864 2.1887736  0.23049627]
 [0.26891863 3.3807254  0.02455889]]
